### PR TITLE
1.4 - ability to route source routed to given destination

### PR DESCRIPTION
**Pull request by wojtek14a**
Example use case:
We have outputs from videohub for mixer inputs named CAM1 - CAM6. There are different inputs routed every time but we need to route those cams for replay system. It is inconvenient to reprogram videohub hardware panel every time for EVS operator so ability to route to given destination (replay input channels) inputs routed to other destinations (CAM1 - CAM6) so that everyone have the same inputs when they say "CAM1".

### CODE REVIEW

**Comment by wojtek14a** [comment]
@krocheck Anyone?

**Comment by wojtek14a** [comment]
@krocheck @haakonnessjoen @willosof @josephdadams @JeffreyDavidsz Please, I really need that :)

**Comment by josephdadams** [comment]
@wojtek14a merging now.

**Comment by krocheck** [comment]
This code doesn't seem to include the action execution.  It seemed to be lost in the merge.

**Comment by josephdadams** [comment]
It looks like it's in master?

**Comment by krocheck** [comment]
ugh ... I hate it when every line in a merge is an overwrite

**Comment by josephdadams** [comment]
I had to resolve a lot of conflicts just to be able to merge it

**Pull request merged**
