### PR TITLE
Return to previous route

### PR DESCRIPTION
**Pull request by peschuster**
Action to be used on 'key up' actions to execute momentary route changes:

image

I tried to follow the style of the module, but are open to suggestions for refactoring if there are other ideas how to implement or name this feature.

### CODE REVIEW

**Comment by krocheck** [comment]
@peschuster I see what you're going for here.  I think the only thing I'm hung up on is the language.  "Route back" is not in the normal 'router lexicon'.  Maybe 'undo route' is more appropriate?

The code seems fine, although the `if (output.fallback !== undefined && output.fallback >= 0) {` might want to be `if (output !== undefined && output.fallback >= 0) {`.  Technically, you define fallback in the declaration, so it should always be there.  Because of how the API works `output` should never be `undefined`, but its good to check that since you already have the `if` block going anyway.

**Comment by peschuster** [comment]
Blackmagic calls the combined action "Momentary Hold Video" (compared to "Latch Video"). But there is no simple term for just the second part of the switching.
Maybe "Return to previous route"? The manual describes the action with the words "... output to return to the previous input". That is what it does technically.

**Comment by krocheck** [comment]
Only question remaining is: have you given this a fair amount of testing?

**Comment by peschuster** [comment]
Yeah, I did a lot of testing and also used it for a while.

There is one limitation for which I haven't figured out a way to solve it: it works great with one button per destination (which is probably the "usual" way and I have never needed any other setup). But with multiple buttons (sources) for a single destination all configured for "momentary hold" it does not work as naturally expected, because only the last routing change is stored for a "fallback". It could be extended to a list/stack, but it is impossible to resolve this stack in all (theoretical) circumstances (pressing and keeping buttons pressed, releasing buttons in a different order than the "key down" actions, route changes for the same destination by other clients in between the button presses...).

So for now i'd just leave it with support for a single concurrent fallback for each destination.

**Comment by krocheck** [comment]
Yeah, that's dicey.  Adding a stack for this condition definitely seems like overkill.  Today I'm a proponent of "let's just do it and if someone complains fix it later" for these types of things. :D

**Comment by krocheck** [comment]
You're still happy with this @peschuster?

**Comment by BaseballJim** [comment]
@krocheck My proposed changes to add ability to read and write  the routing table to a disk file creates a variable that holds the current state of all the routes.  Its updated only when the routing information is sent to the Videohub.  It strikes me that that may help your 'return to previous route' since the start of stack containing routes is already created.  It would only be 1 change deep but maybe that helps?  Just query the route saved in that variable before you change the push down action and replace it on the release action.

**Comment by BaseballJim** [comment]
@peschuster I was running various use cases for this virtually (i.e. in my head) and realized there isn't a way to get a fallback route if the route is done from:  the front panel, any other companion that is running, or BMD's own software.   That may not be horrible in general but I was wondering if anyone knows of any kind of 'notification' that the hardware can send via tcp on changes.  I suppose a polling scheme could be implemented that askes the hardware what its current state is.  Even an update rate of 5sec though would seem like an unwanted drag on the hardware's resources.

**Comment by BaseballJim** [comment]
@peschuster This functionality was incorporated into  commit 540e66b "Add function to save and restore the entire routing table to a disk file" with an added 20 deep stack for each output.  I think this commit is essentially dead now and can be cancelled.

**Pull request closed without merging**
